"""Generate initial .po files for all supported locales."""
import os

TRANSLATIONS: dict[str, dict[str, str]] = {
    "Creating DB schema \u2026": {
        "de_DE": "Datenbankschema wird erstellt \u2026",
        "fr_FR": "Cr\u00e9ation du sch\u00e9ma de base de donn\u00e9es \u2026",
        "es_ES": "Creando esquema de base de datos \u2026",
        "it_IT": "Creazione schema del database \u2026",
        "nl_NL": "Databaseschema wordt aangemaakt \u2026",
        "pl_PL": "Tworzenie schematu bazy danych \u2026",
    },
    "Inserting sample content \u2026": {
        "de_DE": "Beispielinhalte werden eingef\u00fcgt \u2026",
        "fr_FR": "Insertion du contenu d\u2019exemple \u2026",
        "es_ES": "Insertando contenido de muestra \u2026",
        "it_IT": "Inserimento contenuto di esempio \u2026",
        "nl_NL": "Voorbeeldinhoud wordt ingevoegd \u2026",
        "pl_PL": "Wstawianie przyk\u0142adowej tre\u015bci \u2026",
    },
    "\u2713 ArborPress initialised.": {
        "de_DE": "\u2713 ArborPress wurde initialisiert.",
        "fr_FR": "\u2713 ArborPress initialis\u00e9.",
        "es_ES": "\u2713 ArborPress inicializado.",
        "it_IT": "\u2713 ArborPress inizializzato.",
        "nl_NL": "\u2713 ArborPress ge\u00efnitialiseerd.",
        "pl_PL": "\u2713 ArborPress zainicjalizowany.",
    },
    "Next step: arborpress user add": {
        "de_DE": "N\u00e4chster Schritt: arborpress user add",
        "fr_FR": "\u00c9tape suivante\u00a0: arborpress user add",
        "es_ES": "Siguiente paso: arborpress user add",
        "it_IT": "Passo successivo: arborpress user add",
        "nl_NL": "Volgende stap: arborpress user add",
        "pl_PL": "Nast\u0119pny krok: arborpress user add",
    },
    "Start server: arborpress serve --dev": {
        "de_DE": "Server starten: arborpress serve --dev",
        "fr_FR": "D\u00e9marrer le serveur\u00a0: arborpress serve --dev",
        "es_ES": "Iniciar servidor: arborpress serve --dev",
        "it_IT": "Avvia server: arborpress serve --dev",
        "nl_NL": "Server starten: arborpress serve --dev",
        "pl_PL": "Uruchom serwer: arborpress serve --dev",
    },
    "Starting ArborPress on {bind}": {
        "de_DE": "ArborPress wird gestartet auf {bind}",
        "fr_FR": "D\u00e9marrage d\u2019ArborPress sur {bind}",
        "es_ES": "Iniciando ArborPress en {bind}",
        "it_IT": "Avvio di ArborPress su {bind}",
        "nl_NL": "ArborPress wordt gestart op {bind}",
        "pl_PL": "Uruchamianie ArborPress na {bind}",
    },
    "Creating tables \u2026": {
        "de_DE": "Tabellen werden erstellt \u2026",
        "fr_FR": "Cr\u00e9ation des tables \u2026",
        "es_ES": "Creando tablas \u2026",
        "it_IT": "Creazione tabelle \u2026",
        "nl_NL": "Tabellen worden aangemaakt \u2026",
        "pl_PL": "Tworzenie tabel \u2026",
    },
    "Done.": {
        "de_DE": "Fertig.",
        "fr_FR": "Termin\u00e9.",
        "es_ES": "Hecho.",
        "it_IT": "Fatto.",
        "nl_NL": "Klaar.",
        "pl_PL": "Gotowe.",
    },
    "Inserting seed data \u2026": {
        "de_DE": "Seed-Daten werden eingef\u00fcgt \u2026",
        "fr_FR": "Insertion des donn\u00e9es initiales \u2026",
        "es_ES": "Insertando datos iniciales \u2026",
        "it_IT": "Inserimento dati iniziali \u2026",
        "nl_NL": "Seedgegevens worden ingevoegd \u2026",
        "pl_PL": "Wstawianie danych startowych \u2026",
    },
    "Posts inserted:  {n}": {
        "de_DE": "Eingef\u00fcgte Beitr\u00e4ge:  {n}",
        "fr_FR": "Articles ins\u00e9r\u00e9s\u00a0:  {n}",
        "es_ES": "Entradas insertadas:  {n}",
        "it_IT": "Post inseriti:  {n}",
        "nl_NL": "Ingevoegde berichten:  {n}",
        "pl_PL": "Wstawione wpisy:  {n}",
    },
    "Pages inserted:  {n}": {
        "de_DE": "Eingef\u00fcgte Seiten:  {n}",
        "fr_FR": "Pages ins\u00e9r\u00e9es\u00a0:  {n}",
        "es_ES": "P\u00e1ginas insertadas:  {n}",
        "it_IT": "Pagine inserite:  {n}",
        "nl_NL": "Ingevoegde pagina's:  {n}",
        "pl_PL": "Wstawione strony:  {n}",
    },
    "Tags inserted:   {n}": {
        "de_DE": "Eingef\u00fcgte Tags:   {n}",
        "fr_FR": "Tags ins\u00e9r\u00e9s\u00a0:   {n}",
        "es_ES": "Etiquetas insertadas:   {n}",
        "it_IT": "Tag inseriti:   {n}",
        "nl_NL": "Ingevoegde tags:   {n}",
        "pl_PL": "Wstawione tagi:   {n}",
    },
    "DB: {engine} {version}": {
        "de_DE": "DB: {engine} {version}",
        "fr_FR": "DB\u00a0: {engine} {version}",
        "es_ES": "BD: {engine} {version}",
        "it_IT": "DB: {engine} {version}",
        "nl_NL": "DB: {engine} {version}",
        "pl_PL": "BD: {engine} {version}",
    },
    "FTS: {provider}": {
        "de_DE": "Volltextsuche: {provider}",
        "fr_FR": "Recherche plein texte\u00a0: {provider}",
        "es_ES": "B\u00fasqueda de texto completo: {provider}",
        "it_IT": "Ricerca full-text: {provider}",
        "nl_NL": "Volledige tekst zoeken: {provider}",
        "pl_PL": "Wyszukiwanie pe\u0142notekstowe: {provider}",
    },
    "Status: OK": {
        "de_DE": "Status: OK",
        "fr_FR": "Statut\u00a0: OK",
        "es_ES": "Estado: OK",
        "it_IT": "Stato: OK",
        "nl_NL": "Status: OK",
        "pl_PL": "Stan: OK",
    },
    "DB error: {exc}": {
        "de_DE": "DB-Fehler: {exc}",
        "fr_FR": "Erreur DB\u00a0: {exc}",
        "es_ES": "Error de BD: {exc}",
        "it_IT": "Errore DB: {exc}",
        "nl_NL": "DB-fout: {exc}",
        "pl_PL": "B\u0142\u0105d BD: {exc}",
    },
    "Invalid role: {role}. Allowed: {allowed}": {
        "de_DE": "Ung\u00fcltige Rolle: {role}. Erlaubt: {allowed}",
        "fr_FR": "R\u00f4le invalide\u00a0: {role}. Autoris\u00e9\u00a0: {allowed}",
        "es_ES": "Rol inv\u00e1lido: {role}. Permitido: {allowed}",
        "it_IT": "Ruolo non valido: {role}. Consentito: {allowed}",
        "nl_NL": "Ongeldige rol: {role}. Toegestaan: {allowed}",
        "pl_PL": "Nieprawid\u0142owa rola: {role}. Dozwolone: {allowed}",
    },
    "User created: {username!r} [{type}/{role}]": {
        "de_DE": "Benutzer erstellt: {username!r} [{type}/{role}]",
        "fr_FR": "Utilisateur cr\u00e9\u00e9\u00a0: {username!r} [{type}/{role}]",
        "es_ES": "Usuario creado: {username!r} [{type}/{role}]",
        "it_IT": "Utente creato: {username!r} [{type}/{role}]",
        "nl_NL": "Gebruiker aangemaakt: {username!r} [{type}/{role}]",
        "pl_PL": "U\u017cytkownik utworzony: {username!r} [{type}/{role}]",
    },
    "ID: {id}": {
        "de_DE": "ID: {id}",
        "fr_FR": "ID\u00a0: {id}",
        "es_ES": "ID: {id}",
        "it_IT": "ID: {id}",
        "nl_NL": "ID: {id}",
        "pl_PL": "ID: {id}",
    },
    "Next step: arborpress user mfa add {username}": {
        "de_DE": "N\u00e4chster Schritt: arborpress user mfa add {username}",
        "fr_FR": "\u00c9tape suivante\u00a0: arborpress user mfa add {username}",
        "es_ES": "Siguiente paso: arborpress user mfa add {username}",
        "it_IT": "Passo successivo: arborpress user mfa add {username}",
        "nl_NL": "Volgende stap: arborpress user mfa add {username}",
        "pl_PL": "Nast\u0119pny krok: arborpress user mfa add {username}",
    },
    "Really disable user {username!r}?": {
        "de_DE": "Benutzer {username!r} wirklich deaktivieren?",
        "fr_FR": "Vraiment d\u00e9sactiver l\u2019utilisateur {username!r}\u00a0?",
        "es_ES": "\u00bfRealmente deshabilitar el usuario {username!r}?",
        "it_IT": "Disabilitare davvero l\u2019utente {username!r}?",
        "nl_NL": "Gebruiker {username!r} echt uitschakelen?",
        "pl_PL": "Naprawd\u0119 wy\u0142\u0105czy\u0107 u\u017cytkownika {username!r}?",
    },
    "User {username!r} not found.": {
        "de_DE": "Benutzer {username!r} nicht gefunden.",
        "fr_FR": "Utilisateur {username!r} introuvable.",
        "es_ES": "Usuario {username!r} no encontrado.",
        "it_IT": "Utente {username!r} non trovato.",
        "nl_NL": "Gebruiker {username!r} niet gevonden.",
        "pl_PL": "U\u017cytkownik {username!r} nie zosta\u0142 znaleziony.",
    },
    "User {username!r} disabled.": {
        "de_DE": "Benutzer {username!r} deaktiviert.",
        "fr_FR": "Utilisateur {username!r} d\u00e9sactiv\u00e9.",
        "es_ES": "Usuario {username!r} deshabilitado.",
        "it_IT": "Utente {username!r} disabilitato.",
        "nl_NL": "Gebruiker {username!r} uitgeschakeld.",
        "pl_PL": "U\u017cytkownik {username!r} wy\u0142\u0105czony.",
    },
    "User {username!r} unlocked (lock removed, failed_login_count reset).": {
        "de_DE": "Benutzer {username!r} entsperrt (Sperre aufgehoben, Fehlversuchsz\u00e4hler zur\u00fcckgesetzt).",
        "fr_FR": "Utilisateur {username!r} d\u00e9verrouill\u00e9 (verrou supprim\u00e9, compteur r\u00e9initialis\u00e9).",
        "es_ES": "Usuario {username!r} desbloqueado (bloqueo eliminado, contador restablecido).",
        "it_IT": "Utente {username!r} sbloccato (blocco rimosso, contatore azzerato).",
        "nl_NL": "Gebruiker {username!r} ontgrendeld (vergrendeling verwijderd, teller gereset).",
        "pl_PL": "U\u017cytkownik {username!r} odblokowany (blokada usuni\u0119ta, licznik zresetowany).",
    },
    "User {username!r}: no active lock, failed_login_count reset to 0.": {
        "de_DE": "Benutzer {username!r}: keine aktive Sperre, Fehlversuchsz\u00e4hler auf 0 zur\u00fcckgesetzt.",
        "fr_FR": "Utilisateur {username!r}\u00a0: pas de verrou actif, compteur r\u00e9initialis\u00e9 \u00e0 0.",
        "es_ES": "Usuario {username!r}: sin bloqueo activo, contador restablecido a 0.",
        "it_IT": "Utente {username!r}: nessun blocco attivo, contatore azzerato a 0.",
        "nl_NL": "Gebruiker {username!r}: geen actieve vergrendeling, teller gereset naar 0.",
        "pl_PL": "U\u017cytkownik {username!r}: brak aktywnej blokady, licznik zresetowany do 0.",
    },
    "Role: {old} \u2192 {new} for {username!r}": {
        "de_DE": "Rolle: {old} \u2192 {new} f\u00fcr {username!r}",
        "fr_FR": "R\u00f4le\u00a0: {old} \u2192 {new} pour {username!r}",
        "es_ES": "Rol: {old} \u2192 {new} para {username!r}",
        "it_IT": "Ruolo: {old} \u2192 {new} per {username!r}",
        "nl_NL": "Rol: {old} \u2192 {new} voor {username!r}",
        "pl_PL": "Rola: {old} \u2192 {new} dla {username!r}",
    },
    "No users found.": {
        "de_DE": "Keine Benutzer gefunden.",
        "fr_FR": "Aucun utilisateur trouv\u00e9.",
        "es_ES": "No se encontraron usuarios.",
        "it_IT": "Nessun utente trovato.",
        "nl_NL": "Geen gebruikers gevonden.",
        "pl_PL": "Nie znaleziono u\u017cytkownik\u00f3w.",
    },
    "Username": {
        "de_DE": "Benutzername",
        "fr_FR": "Nom d\u2019utilisateur",
        "es_ES": "Nombre de usuario",
        "it_IT": "Nome utente",
        "nl_NL": "Gebruikersnaam",
        "pl_PL": "Nazwa u\u017cytkownika",
    },
    "Role": {
        "de_DE": "Rolle",
        "fr_FR": "R\u00f4le",
        "es_ES": "Rol",
        "it_IT": "Ruolo",
        "nl_NL": "Rol",
        "pl_PL": "Rola",
    },
    "Type": {
        "de_DE": "Typ",
        "fr_FR": "Type",
        "es_ES": "Tipo",
        "it_IT": "Tipo",
        "nl_NL": "Type",
        "pl_PL": "Typ",
    },
    "Active": {
        "de_DE": "Aktiv",
        "fr_FR": "Actif",
        "es_ES": "Activo",
        "it_IT": "Attivo",
        "nl_NL": "Actief",
        "pl_PL": "Aktywny",
    },
    "Email": {
        "de_DE": "E-Mail",
        "fr_FR": "E-mail",
        "es_ES": "Correo electr\u00f3nico",
        "it_IT": "E-mail",
        "nl_NL": "E-mail",
        "pl_PL": "E-mail",
    },
    "New break-glass password": {
        "de_DE": "Neues Break-Glass-Passwort",
        "fr_FR": "Nouveau mot de passe break-glass",
        "es_ES": "Nueva contrase\u00f1a break-glass",
        "it_IT": "Nuova password break-glass",
        "nl_NL": "Nieuw break-glass wachtwoord",
        "pl_PL": "Nowe has\u0142o break-glass",
    },
    "Confirm break-glass password": {
        "de_DE": "Break-Glass-Passwort best\u00e4tigen",
        "fr_FR": "Confirmer le mot de passe break-glass",
        "es_ES": "Confirmar contrase\u00f1a break-glass",
        "it_IT": "Conferma password break-glass",
        "nl_NL": "Break-glass wachtwoord bevestigen",
        "pl_PL": "Potwierd\u017a has\u0142o break-glass",
    },
    "Passwords do not match.": {
        "de_DE": "Passw\u00f6rter stimmen nicht \u00fcberein.",
        "fr_FR": "Les mots de passe ne correspondent pas.",
        "es_ES": "Las contrase\u00f1as no coinciden.",
        "it_IT": "Le password non corrispondono.",
        "nl_NL": "Wachtwoorden komen niet overeen.",
        "pl_PL": "Has\u0142a nie s\u0105 zgodne.",
    },
    "zxcvbn score:            {score}/4": {
        "de_DE": "zxcvbn-Score:            {score}/4",
        "fr_FR": "Score zxcvbn\u00a0:            {score}/4",
        "es_ES": "Puntuaci\u00f3n zxcvbn:       {score}/4",
        "it_IT": "Punteggio zxcvbn:        {score}/4",
        "nl_NL": "zxcvbn-score:            {score}/4",
        "pl_PL": "Wynik zxcvbn:            {score}/4",
    },
    "Warning:                 {warning}": {
        "de_DE": "Warnung:                 {warning}",
        "fr_FR": "Avertissement\u00a0:          {warning}",
        "es_ES": "Advertencia:             {warning}",
        "it_IT": "Avvertenza:              {warning}",
        "nl_NL": "Waarschuwing:            {warning}",
        "pl_PL": "Ostrze\u017cenie:             {warning}",
    },
    "Suggestions:             {suggestions}": {
        "de_DE": "Vorschl\u00e4ge:              {suggestions}",
        "fr_FR": "Suggestions\u00a0:            {suggestions}",
        "es_ES": "Sugerencias:             {suggestions}",
        "it_IT": "Suggerimenti:            {suggestions}",
        "nl_NL": "Suggesties:              {suggestions}",
        "pl_PL": "Sugestie:                {suggestions}",
    },
    "Crack time (offline):    {time}": {
        "de_DE": "Crackzeit (offline):     {time}",
        "fr_FR": "Temps de crack (hors ligne)\u00a0: {time}",
        "es_ES": "Tiempo de crackeo (sin conexi\u00f3n): {time}",
        "it_IT": "Tempo di crack (offline): {time}",
        "nl_NL": "Kraaktijd (offline):     {time}",
        "pl_PL": "Czas \u0142amania (offline):  {time}",
    },
    "Use either --password or --generate, not both.": {
        "de_DE": "Bitte nur --password oder --generate verwenden, nicht beides.",
        "fr_FR": "Utilisez --password ou --generate, pas les deux.",
        "es_ES": "Use --password o --generate, no ambos.",
        "it_IT": "Usa --password o --generate, non entrambi.",
        "nl_NL": "Gebruik --password of --generate, niet beide.",
        "pl_PL": "U\u017cyj --password lub --generate, nie obu jednocze\u015bnie.",
    },
    "Invalid break-glass password: {exc}": {
        "de_DE": "Ung\u00fcltiges Break-Glass-Passwort: {exc}",
        "fr_FR": "Mot de passe break-glass invalide\u00a0: {exc}",
        "es_ES": "Contrase\u00f1a break-glass inv\u00e1lida: {exc}",
        "it_IT": "Password break-glass non valida: {exc}",
        "nl_NL": "Ongeldig break-glass wachtwoord: {exc}",
        "pl_PL": "Nieprawid\u0142owe has\u0142o break-glass: {exc}",
    },
    "Password for {username!r} set and activated.": {
        "de_DE": "Passwort f\u00fcr {username!r} gesetzt und aktiviert.",
        "fr_FR": "Mot de passe pour {username!r} d\u00e9fini et activ\u00e9.",
        "es_ES": "Contrase\u00f1a para {username!r} establecida y activada.",
        "it_IT": "Password per {username!r} impostata e attivata.",
        "nl_NL": "Wachtwoord voor {username!r} ingesteld en geactiveerd.",
        "pl_PL": "Has\u0142o dla {username!r} ustawione i aktywowane.",
    },
    "Generated password:      {password}": {
        "de_DE": "Generiertes Passwort:    {password}",
        "fr_FR": "Mot de passe g\u00e9n\u00e9r\u00e9\u00a0:    {password}",
        "es_ES": "Contrase\u00f1a generada:     {password}",
        "it_IT": "Password generata:       {password}",
        "nl_NL": "Gegenereerd wachtwoord:  {password}",
        "pl_PL": "Wygenerowane has\u0142o:      {password}",
    },
}

LANG_HEADERS: dict[str, tuple[str, str]] = {
    "de_DE": ("de-DE", "Deutsch"),
    "en_GB": ("en-GB", "English"),
    "fr_FR": ("fr-FR", "Fran\u00e7ais"),
    "es_ES": ("es-ES", "Espa\u00f1ol"),
    "it_IT": ("it-IT", "Italiano"),
    "nl_NL": ("nl-NL", "Nederlands"),
    "pl_PL": ("pl-PL", "Polski"),
}

BASE = os.path.join(os.path.dirname(__file__), "..", "arborpress", "translations")


def _escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


for fs_lang, (bcp, lang_name) in LANG_HEADERS.items():
    po_path = os.path.join(BASE, fs_lang, "LC_MESSAGES", "arborpress.po")
    os.makedirs(os.path.dirname(po_path), exist_ok=True)
    parts = [
        f"# ArborPress translations \u2013 {bcp} ({lang_name})",
        "# This file is distributed under the AGPL-3.0-or-later license.",
        "#",
        'msgid ""',
        'msgstr ""',
        '"Project-Id-Version: arborpress 0.1.0\\n"',
        '"Report-Msgid-Bugs-To: \\n"',
        '"POT-Creation-Date: 2026-04-22 00:00+0000\\n"',
        '"PO-Revision-Date: 2026-04-22 00:00+0000\\n"',
        '"Last-Translator: FULL NAME <EMAIL@ADDRESS>\\n"',
        f'"Language: {bcp}\\n"',
        f'"Language-Team: {bcp} <>\\n"',
        '"MIME-Version: 1.0\\n"',
        '"Content-Type: text/plain; charset=UTF-8\\n"',
        '"Content-Transfer-Encoding: 8bit\\n"',
        "",
    ]
    for msgid, trans in TRANSLATIONS.items():
        msgstr = msgid if fs_lang == "en_GB" else trans.get(fs_lang, "")
        parts.append(f'msgid "{_escape(msgid)}"')
        parts.append(f'msgstr "{_escape(msgstr)}"')
        parts.append("")

    with open(po_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(parts))
    print(f"Written {len(TRANSLATIONS)} strings \u2192 {po_path}")
